import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import {
  launchBrowser,
  createPage,
} from "../lib/scraper-utils.js";

// ESM doesn't define __dirname; derive it from import.meta.url for allowlist file lookup
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * RP-11 (final): Load the 84116 (Rose Park) parcel-ID allowlist generated by
 * scraper/src/scripts/build-rose-park-parcel-allowlist.ts from UGRC's
 * SaltLake_County_Addresses layer.
 *
 * TODO: Once slc-parcel-neighborhood-map.json has been validated in production
 * for a full scrape cycle (1-2 weeks), this function and the allowlist file
 * can be removed. The new county-wide map (getSlcNeighborhoodMap) is a superset
 * that covers 84116/Rose Park as well as all other SLC County zips.
 *
 * @deprecated Use getSlcNeighborhoodMap() instead.
 */
let cachedRoseParkAllowlist: Set<string> | null = null;
function getRoseParkAllowlist(): Set<string> {
  if (cachedRoseParkAllowlist) return cachedRoseParkAllowlist;
  const candidatePaths = [
    path.resolve(process.cwd(), "data", "rose-park-parcel-allowlist.json"),
    path.resolve(process.cwd(), "scraper", "data", "rose-park-parcel-allowlist.json"),
    path.resolve(__dirname, "..", "..", "data", "rose-park-parcel-allowlist.json"),
  ];
  for (const p of candidatePaths) {
    try {
      const raw = fs.readFileSync(p, "utf-8");
      const parsed = JSON.parse(raw) as { parcelIds: string[] };
      cachedRoseParkAllowlist = new Set(parsed.parcelIds);
      console.log(`[utah-legals] Loaded Rose Park parcel allowlist (${cachedRoseParkAllowlist.size} parcels) from ${p}`);
      return cachedRoseParkAllowlist;
    } catch {
      // try next path
    }
  }
  console.warn(
    `[utah-legals] WARNING: Rose Park parcel allowlist not found in any candidate path. Run scraper/src/scripts/build-rose-park-parcel-allowlist.ts to generate.`
  );
  cachedRoseParkAllowlist = new Set();
  return cachedRoseParkAllowlist;
}

/**
 * SLC county-wide parcel -> {zip, city} map.
 * Generated by build-slc-parcel-neighborhood-map.ts from UGRC SaltLake_County_Addresses.
 * Covers ALL Salt Lake County parcels, not just 84116.
 * Loaded once at first SLC notice, then cached for the lifetime of the scraper run.
 */
interface SlcParcelEntry {
  zip: string;
  city: string;
}
interface SlcNeighborhoodMapFile {
  generatedAt: string;
  source: string;
  addressCount: number;
  parcelCount: number;
  parcels: Record<string, SlcParcelEntry>;
}

let cachedSlcNeighborhoodMap: Map<string, SlcParcelEntry> | null = null;
function getSlcNeighborhoodMap(): Map<string, SlcParcelEntry> {
  if (cachedSlcNeighborhoodMap) return cachedSlcNeighborhoodMap;
  const candidatePaths = [
    path.resolve(process.cwd(), "data", "slc-parcel-neighborhood-map.json"),
    path.resolve(process.cwd(), "scraper", "data", "slc-parcel-neighborhood-map.json"),
    path.resolve(__dirname, "..", "..", "data", "slc-parcel-neighborhood-map.json"),
  ];
  for (const p of candidatePaths) {
    try {
      const raw = fs.readFileSync(p, "utf-8");
      const parsed = JSON.parse(raw) as SlcNeighborhoodMapFile;
      cachedSlcNeighborhoodMap = new Map(Object.entries(parsed.parcels));
      console.log(
        `[utah-legals] Loaded SLC neighborhood map (${cachedSlcNeighborhoodMap.size} parcels) from ${p} (generated ${parsed.generatedAt})`
      );
      return cachedSlcNeighborhoodMap;
    } catch {
      // try next path
    }
  }
  // Fall back to the 84116 allowlist if the county-wide map hasn't been generated yet.
  // This preserves the Phase 25.5 behavior for Rose Park notices while the new map is built.
  console.warn(
    `[utah-legals] WARNING: SLC neighborhood map not found. Falling back to 84116-only Rose Park allowlist. ` +
    `Run scraper/src/scripts/build-slc-parcel-neighborhood-map.ts to generate.`
  );
  const roseParkAllowlist = getRoseParkAllowlist();
  const fallbackMap = new Map<string, SlcParcelEntry>();
  for (const parcelId of roseParkAllowlist) {
    fallbackMap.set(parcelId, { zip: "84116", city: "Rose Park" });
  }
  cachedSlcNeighborhoodMap = fallbackMap;
  return cachedSlcNeighborhoodMap;
}

/**
 * Normalize a parcel ID for allowlist comparison: strip hyphens, dots, and
 * spaces, uppercase. Matches the normalizer used by the allowlist build script
 * and by import-ugrc-assessor.mjs so all three speak the same canonical form.
 *
 * Utah Legals SLC parcels appear hyphenated (`26-24-406-084-0000`) while the
 * UGRC allowlist stores bare numeric (`26244060840000`). Both normalize to
 * `26244060840000` for matching.
 */
function normalizeParcelIdForAllowlist(raw: string | null | undefined): string | null {
  if (!raw) return null;
  // Strip whitespace, hyphens, dots first
  let cleaned = raw.replace(/[\s\-\.]/g, "").toUpperCase().trim();
  // Defensive: extractParcelId() Branch 2 (label-based) sometimes captures
  // trailing letters when the source text has no separator (e.g.
  // "Tax Serial Number: 21171790050000IMPORTANT NOTICE..." captures
  // "21171790050000IMPORTANT"). Strip MULTI-letter trailing sequences only —
  // single trailing letters are legitimate Utah parcel suffixes
  // (e.g. Emery `01-0211-002C` is distinct from `01-0211-002`).
  cleaned = cleaned.replace(/[A-Z]{2,}$/, "");
  return cleaned.length > 0 ? cleaned : null;
}

// County checkbox indexes in the Utah Legals checkbox list (0-based, verified from HTML)
// Beaver=0, Box Elder=1, Cache=2, Carbon=3, Daggett=4, Davis=5, Duchesne=6,
// Emery=7, Garfield=8, Grand=9, Iron=10, Juab=11, Kane=12, Millard=13,
// Morgan=14, Piute=15, Rich=16, Salt Lake=17, Salt Lake/Utah=18 (WRONG — combined, do NOT use index 18)
const TARGET_COUNTIES: Array<{ index: number; name: string }> = [
  { index: 3,  name: "carbon" },
  { index: 7,  name: "emery" },
  { index: 11, name: "juab" },
  { index: 13, name: "millard" },
  { index: 17, name: "salt lake" }, // Salt Lake County only — NOT index 18 ("Salt Lake/Utah" combined)
];

export interface UtahLegalsNotice {
  title: string;
  county: string;
  city: string;
  noticeDate?: string;
  bodyText: string;
  detailUrl?: string;
  /** Extracted property address from notice snippet, if found */
  propertyAddress?: string;
  /** Extracted owner/grantor name from notice snippet, if found */
  ownerName?: string;
  /** Extracted parcel/serial number from notice snippet, if found */
  parcelId?: string;
  /** Property zip from UGRC neighborhood map for SLC notices; undefined for rural counties */
  zip?: string;
}

/**
 * Extract a property address from trustee sale notice text.
 * Looks for patterns like "commonly known as 123 Main St, Price, UT"
 * or "property located at ..." or street address patterns.
 */
/**
 * Scan the notice snippet for all Utah ZIP codes (84xxx range).
 * Used by RP-11 to filter SLC notices to those whose property is actually in 84116.
 * Returns deduped, ordered-by-first-appearance list. Empty array = no zips found.
 */
function extractAllUtahZips(text: string): string[] {
  const matches = text.match(/\b84\d{3}\b/g);
  if (!matches) return [];
  return Array.from(new Set(matches));
}

function extractAddress(text: string): string | undefined {
  // Pattern: "commonly known as <address>"
  const knownAs = text.match(/commonly known as\s+([^,\n]+(?:,[^,\n]+)?)/i);
  if (knownAs) return knownAs[1].trim();

  // Pattern: "property located at <address>"
  const locatedAt = text.match(/property (?:located|situate[d]?) at\s+([^,\n]+(?:,[^,\n]+)?)/i);
  if (locatedAt) return locatedAt[1].trim();

  // Pattern: street address (number + direction/street name)
  const streetAddr = text.match(/\b(\d+\s+(?:[A-Z]\w+\s+){1,4}(?:St(?:reet)?|Ave(?:nue)?|Rd|Road|Dr(?:ive)?|Blvd|Ln|Lane|Ct|Court|Way|Cir|Pl(?:ace)?)[.,\s][^,\n]{1,40})/i);
  if (streetAddr) return streetAddr[1].trim();

  return undefined;
}

/**
 * Extract owner/grantor name from trustee sale notice text.
 */
function extractOwnerName(text: string): string | undefined {
  const trustor = text.match(/(?:Trustor|Grantor)[s]?:?\s+([A-Z][A-Za-z\s,.']+?)(?:\n|,|\band\b|$)/i);
  if (trustor) return trustor[1].trim().replace(/,\s*$/, "");

  const madeBy = text.match(/(?:deed of trust|trust deed) made by\s+([A-Z][A-Za-z\s,.']+?)(?:\s+to\s+|\n|$)/i);
  if (madeBy) return madeBy[1].trim();

  return undefined;
}

/**
 * Trim trailing MULTI-letter alpha sequences from a captured parcel ID. When
 * source text has no separator after the parcel (e.g. "Tax Serial Number:
 * 21171790050000IMPORTANT NOTICE..."), Branch 2's greedy `[\w-]+` pattern
 * captures into the next word.
 *
 * IMPORTANT: only strip 2+ trailing letters. Single trailing letters are
 * legitimate Utah parcel suffixes (e.g. Emery `01-0211-002C` denotes a
 * subdivided parcel — `002`, `002A`, `002B`, `002C` are all distinct).
 * Stripping single letters would collapse distinct properties into duplicates.
 */
function cleanParcelId(raw: string): string {
  return raw.trim().replace(/[A-Za-z]{2,}$/, "");
}

/**
 * Extract parcel / serial number from notice text.
 * Supports A.P.N., Parcel No., Serial No., Tax ID formats.
 */
function extractParcelId(text: string): string | undefined {
  // Pattern: "A.P.N.: XX-XXX-XXXX" (common in Utah trustee sale notices)
  const apn = text.match(/A\.P\.N\.?:?\s*([A-Z0-9][\w\-./]{3,})/i);
  if (apn) return cleanParcelId(apn[1]);

  // Pattern: "Parcel No." or "Serial No." or "Tax ID"
  const parcelNo = text.match(/(?:Parcel|Serial|Tax ID|Parcel No\.?|Serial No\.?)[:\s#]+([A-Z0-9][\w-]{3,})/i);
  if (parcelNo) return cleanParcelId(parcelNo[1]);

  // Pattern: Carbon-style parcel XX-XXXX-XXXX
  const carbonParcel = text.match(/\b(\d{2}-\d{4}-\d{4})\b/);
  if (carbonParcel) return carbonParcel[1];

  // Branch 4: SLC multi-segment bare pattern (defensive fallback — Branch 2 catches labeled SLC parcels)
  // Matches: 26-24-406-084-0000, 08-22-327-004-0000 (format: DD-DD-DDD-DDD-DDDD)
  // Branch 2 handles labeled SLC parcels (Serial No., Tax Serial Number, etc.)
  // Branch 4 catches any unlabeled SLC bare number not matched by Branch 3.
  const slcParcel = text.match(/\b(\d{2}-\d{1,3}-\d{3,4}-\d{3,4}-\d{3,4})\b/);
  if (slcParcel) return slcParcel[1];

  return undefined;
}

/** Cities whose Utah Legals notices indicate a property in the 84116 zip-code area (Rose Park / West SLC). */
// RP-11 (original): city-name allowlist — superseded 2026-04-26 by extractAllUtahZips()
// after dry-run confirmed all SLC notices show city="Salt Lake City" regardless of
// property location. Kept here as historical reference; no longer referenced in code.
const SLC_84116_CITIES_LEGACY = new Set(['salt lake city', 'rose park', 'north salt lake']);
void SLC_84116_CITIES_LEGACY;  // suppress unused-var lint

/**
 * Scrapes Utah Legals (utahlegals.com) for trustee sale / foreclosure notices
 * in Carbon, Emery, Juab, and Millard counties.
 *
 * Uses Playwright with the correct interaction sequence for the ASP.NET WebForms site:
 * 1. Select "Foreclosures" from the quick-search dropdown (triggers __doPostBack redirect)
 * 2. Expand the County filter panel (click label.header to show div#countyDiv)
 * 3. For each target county: set checkbox.checked=true, then call __doPostBack via JS
 * 4. Click the search button (id="ctl00_ContentPlaceHolder1_as1_btnGo")
 * 5. Parse results from the WSExtendedGridNP1 grid (input.viewButton + td.info cells)
 *
 * NOTE: Does NOT visit individual detail pages because Details.aspx requires
 * reCAPTCHA completion. All usable data (parcel, county, city, snippet) is
 * extracted from the search results list.
 *
 * @returns Array of UtahLegalsNotice objects
 */
export async function scrapeUtahLegalsForeclosures(): Promise<UtahLegalsNotice[]> {
  const startTime = Date.now();
  const notices: UtahLegalsNotice[] = [];
  const tag = "[utah-legals]";

  const browser = await launchBrowser();

  try {
    const page = await createPage(browser);
    // Use a wide viewport so the footer doesn't overlay the county checkboxes
    await page.setViewportSize({ width: 1280, height: 900 });

    // Navigate to search page — ASP.NET will redirect to a session URL
    await page.goto("https://www.utahlegals.com/Search.aspx", {
      waitUntil: "networkidle",
      timeout: 60000,
    });

    console.log(`${tag} Page loaded: ${page.url()}`);

    // Step 1: Select "Foreclosures" (value "3") from the quick-search dropdown.
    // This triggers a __doPostBack which redirects and sets the category filter.
    const ddl = await page.$(
      "#ctl00_ContentPlaceHolder1_as1_ddlPopularSearches"
    );
    if (!ddl) {
      console.log(`${tag} Quick search dropdown not found — aborting`);
      return notices;
    }
    await ddl.selectOption("3");
    await page.waitForLoadState("networkidle", { timeout: 30000 });
    await page.waitForTimeout(2000);
    console.log(`${tag} Foreclosures category selected, URL: ${page.url()}`);

    // Step 2: Expand the County filter panel (div#countyDiv starts collapsed).
    try {
      await page.click(
        "#ctl00_ContentPlaceHolder1_as1_divCounty label.header"
      );
      await page.waitForTimeout(500);
      console.log(`${tag} County panel expanded`);
    } catch (err) {
      console.log(`${tag} Could not expand county panel:`, err);
    }

    // Step 3: Check each target county checkbox.
    // Standard Playwright .check() fails because the footer element overlaps the checkboxes
    // and because the ASP.NET __doPostBack requires the checkbox to already be in the
    // checked state when the form is serialized.
    // Solution: set checked=true in the DOM, then trigger __doPostBack via page.evaluate().
    for (const county of TARGET_COUNTIES) {
      try {
        const checked = await page.evaluate((idx) => {
          const cb = document.getElementById(
            `ctl00_ContentPlaceHolder1_as1_lstCounty_${idx}`
          ) as HTMLInputElement | null;
          if (!cb) return false;
          if (cb.checked) return true; // already checked
          cb.checked = true;
          // Trigger the async UpdatePanel postback that the onclick attribute would fire.
          // __doPostBack is an ASP.NET WebForms global injected at runtime by ScriptManager.
          // We cast to any to avoid TS2304 ("Cannot find name '__doPostBack'").
          const doPostBack = (window as unknown as Record<string, unknown>)["__doPostBack"] as
            | ((target: string, argument: string) => void)
            | undefined;
          if (typeof doPostBack === "function") {
            doPostBack(
              `ctl00$ContentPlaceHolder1$as1$lstCounty$${idx}`,
              ""
            );
          }
          return true;
        }, county.index);

        if (checked) {
          await page.waitForTimeout(500);
          await page.waitForLoadState("networkidle", { timeout: 15000 });
          await page.waitForTimeout(800);
          console.log(`${tag} Checked county: ${county.name} (index ${county.index})`);
        } else {
          console.log(`${tag} County checkbox not found: ${county.name} (index ${county.index})`);
        }
      } catch (err) {
        console.log(`${tag} Error checking county ${county.name}:`, err);
      }
    }

    // Step 4: Click the search button.
    // The button has value="" and class="goButton" - NOT value="Search".
    // Use page.evaluate to avoid footer overlay interception.
    try {
      await page.evaluate(() => {
        const btn = document.getElementById(
          "ctl00_ContentPlaceHolder1_as1_btnGo"
        ) as HTMLInputElement | null;
        if (btn) (btn as HTMLElement).click();
      });
      await page.waitForLoadState("networkidle", { timeout: 30000 });
      await page.waitForTimeout(3000);
      console.log(`${tag} Search submitted`);
    } catch (err) {
      console.log(`${tag} Error clicking search button:`, err);
    }

    // Step 5: Parse results and paginate.
    let hasNextPage = true;
    let pageNum = 0;

    while (hasNextPage && pageNum < 20) {
      pageNum++;

      // Extract all notice rows from the WSExtendedGridNP1 grid.
      // Each row is a table.nested inside the wsResultsGrid.
      // - viewButton input has onclick="location.href='Details.aspx?SID=...&ID=...'"
      // - td.info .left: publication name and date
      // - td.info .right: City/County (hidden in CSS but still in DOM)
      // - td[colspan="3"]: snippet text (~300 chars) including A.P.N. / trustee info
      const pageResults = await page.$$eval(
        "table.wsResultsGrid table.nested",
        (tables: Element[]) => {
          return tables
            .map((t) => {
              const viewBtn = t.querySelector(
                'input.viewButton[onclick*="Details.aspx"]'
              ) as HTMLInputElement | null;
              if (!viewBtn) return null;

              const onclick = viewBtn.getAttribute("onclick") ?? "";
              const idMatch = onclick.match(/ID=(\d+)/);
              const sidMatch = onclick.match(/SID=([^&']+)/);
              if (!idMatch) return null;

              const infoCell = t.querySelector("td.info");
              const pubEl = infoCell?.querySelector("strong");
              const publication = pubEl?.textContent?.trim() ?? "";
              const leftText =
                infoCell
                  ?.querySelector(".left")
                  ?.textContent?.replace(publication, "")
                  .trim() ?? "";
              const rightText =
                infoCell?.querySelector(".right")?.textContent?.trim() ?? "";

              // Extract city and county from the hidden .right cell text
              // Format: "City: <city>\n                                    County: <county>"
              const cityMatch = rightText.match(/City:\s*([^\n]+)/);
              const countyMatch = rightText.match(/County:\s*([^\n]+)/);
              const city = cityMatch?.[1]?.trim() ?? "";
              const county = countyMatch?.[1]?.trim() ?? "";

              const snippet =
                t
                  .querySelector("td[colspan='3']")
                  ?.textContent?.trim() ?? "";

              return {
                noticeId: idMatch[1],
                sid: sidMatch?.[1] ?? "",
                publication,
                dateText: leftText,
                city,
                county,
                snippet: snippet.substring(0, 2000),
              };
            })
            .filter((r): r is NonNullable<typeof r> => r !== null);
        }
      );

      console.log(
        `${tag} Page ${pageNum}: found ${pageResults.length} notices`
      );

      for (const result of pageResults) {
        const snippet = result.snippet;
        const countyLower = result.county.toLowerCase();

        // Filter: only keep notices from our target counties
        const isTargetCounty = TARGET_COUNTIES.some(
          (c) => c.name === countyLower
        );
        if (!isTargetCounty) {
          console.log(
            `${tag} Skipping non-target county: ${result.county} (ID: ${result.noticeId})`
          );
          continue;
        }

        // Filter: only keep trustee sale / foreclosure notices
        // (results may include summons, ordinances, etc. because Foreclosures
        //  category can include all notice types from the selected publications)
        const isForeclosure =
          snippet.toLowerCase().includes("trustee") ||
          snippet.toLowerCase().includes("foreclos") ||
          snippet.toLowerCase().includes("notice of default") ||
          snippet.toLowerCase().includes("nod");
        if (!isForeclosure) {
          console.log(
            `${tag} Skipping non-foreclosure notice in ${result.county} (ID: ${result.noticeId}): ${snippet.substring(0, 80)}`
          );
          continue;
        }

        // Path A (2026-04-17): For Salt Lake County notices, look up the parcel ID
        // in the county-wide SLC neighborhood map (slc-parcel-neighborhood-map.json),
        // which covers ALL SLC County zips — not just 84116.
        //
        // Reliable geographic filter rationale:
        //   - Utah Legals notice city = law-firm jurisdiction (always "Salt Lake City"), useless
        //   - Snippet rarely contains property zip (300-char truncation)
        //   - UGRC SaltLake_County_Addresses has definitive ParcelID + ZipCode mapping
        //
        // Notices whose parcel ID is found in the map: accepted, tagged with correct
        //   neighborhood city (Rose Park, Sandy, Midvale, Holladay, etc.) + zip.
        // Notices whose parcel ID can't be extracted: skipped (can't confirm location).
        // Notices with an extracted parcel ID not in the map: skipped with a diagnostic
        //   log (new subdivision, data gap, or parcel ID parse error).
        let propertyZip: string | undefined;
        let propertyCity: string | undefined;
        if (countyLower === 'salt lake') {
          const neighborhoodMap = getSlcNeighborhoodMap();
          const rawParcelId = extractParcelId(snippet);
          const normalized = normalizeParcelIdForAllowlist(rawParcelId);
          if (!normalized) {
            console.log(
              `${tag} SLC notice excluded (no parcel ID extracted from snippet) (ID: ${result.noticeId})`
            );
            continue;
          }
          const entry = neighborhoodMap.get(normalized);
          if (!entry) {
            console.log(
              `${tag} SLC notice excluded (parcel ${rawParcelId} -> ${normalized} not in SLC neighborhood map — new subdivision or data gap?) (ID: ${result.noticeId})`
            );
            continue;
          }
          console.log(
            `${tag} SLC notice ACCEPTED — parcel ${rawParcelId} -> ${normalized} mapped to ${entry.city} (${entry.zip}) (ID: ${result.noticeId})`
          );
          propertyZip = entry.zip;
          propertyCity = entry.city;
        }

        // Parse notice date from dateText (e.g., "Friday, March 20, 2026" or "Wednesday, Mar 18, 2026")
        let noticeDate: string | undefined;
        if (result.dateText) {
          const d = new Date(result.dateText.replace(/\s+/g, " ").trim());
          if (!isNaN(d.getTime())) {
            noticeDate = d.toISOString().split("T")[0];
          }
        }

        const detailUrl = result.sid
          ? `https://www.utahlegals.com/Details.aspx?SID=${result.sid}&ID=${result.noticeId}`
          : `https://www.utahlegals.com/Details.aspx?ID=${result.noticeId}`;

        const notice: UtahLegalsNotice = {
          title: `NOTICE OF TRUSTEE'S SALE - ${result.county} County`,
          county: countyLower,
          // For SLC notices, override the law-firm city with the UGRC-derived neighborhood.
          // For rural counties, use the city value from the search results as-is.
          city: propertyCity ?? result.city,
          noticeDate,
          bodyText: snippet,
          detailUrl,
          propertyAddress: extractAddress(snippet),
          ownerName: extractOwnerName(snippet),
          parcelId: extractParcelId(snippet),
          zip: propertyZip,  // Path A: zip from UGRC map (covers all SLC County zips, not just 84116)
        };

        notices.push(notice);
        console.log(
          `${tag} Notice ID:${result.noticeId} county:${notice.county} city:${notice.city} parcel:${notice.parcelId ?? "none"} addr:${notice.propertyAddress ?? "none"}`
        );
      }

      // Check for next page
      const nextBtn = await page.$(
        "#ctl00_ContentPlaceHolder1_WSExtendedGridNP1_GridView1_ctl01_btnNext:not([disabled])"
      );
      if (nextBtn && pageResults.length > 0) {
        try {
          await page.evaluate(() => {
            const btn = document.getElementById(
              "ctl00_ContentPlaceHolder1_WSExtendedGridNP1_GridView1_ctl01_btnNext"
            ) as HTMLInputElement | null;
            if (btn) btn.click();
          });
          await page.waitForLoadState("networkidle", { timeout: 20000 });
          await page.waitForTimeout(1500);
          console.log(`${tag} Navigated to page ${pageNum + 1}`);
        } catch (err) {
          console.log(`${tag} Pagination error:`, err);
          hasNextPage = false;
        }
      } else {
        hasNextPage = false;
      }
    }
  } finally {
    await browser.close();
  }

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(
    `${tag} Complete: ${notices.length} notices processed, ${elapsed}s elapsed`
  );

  return notices;
}
